// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: proto/meta.proto

package metapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBucketReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
}

func (x *CreateBucketReq) Reset() {
	*x = CreateBucketReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBucketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketReq) ProtoMessage() {}

func (x *CreateBucketReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketReq.ProtoReflect.Descriptor instead.
func (*CreateBucketReq) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBucketReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type CreateBucketResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBucketResp) Reset() {
	*x = CreateBucketResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBucketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResp) ProtoMessage() {}

func (x *CreateBucketResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResp.ProtoReflect.Descriptor instead.
func (*CreateBucketResp) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{1}
}

type DeleteBucketReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
}

func (x *DeleteBucketReq) Reset() {
	*x = DeleteBucketReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBucketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketReq) ProtoMessage() {}

func (x *DeleteBucketReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketReq.ProtoReflect.Descriptor instead.
func (*DeleteBucketReq) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBucketReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type DeleteBucketResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBucketResp) Reset() {
	*x = DeleteBucketResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBucketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketResp) ProtoMessage() {}

func (x *DeleteBucketResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketResp.ProtoReflect.Descriptor instead.
func (*DeleteBucketResp) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{3}
}

type GetFilesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
}

func (x *GetFilesReq) Reset() {
	*x = GetFilesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesReq) ProtoMessage() {}

func (x *GetFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesReq.ProtoReflect.Descriptor instead.
func (*GetFilesReq) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{4}
}

func (x *GetFilesReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type GetFilesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []string `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *GetFilesResp) Reset() {
	*x = GetFilesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesResp) ProtoMessage() {}

func (x *GetFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesResp.ProtoReflect.Descriptor instead.
func (*GetFilesResp) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{5}
}

func (x *GetFilesResp) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type CreateFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket      string                    `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	File        string                    `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	ContentType string                    `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Chunks      []*ChunkFilenameWithShard `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`
}

func (x *CreateFileReq) Reset() {
	*x = CreateFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileReq) ProtoMessage() {}

func (x *CreateFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileReq.ProtoReflect.Descriptor instead.
func (*CreateFileReq) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{6}
}

func (x *CreateFileReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CreateFileReq) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *CreateFileReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateFileReq) GetChunks() []*ChunkFilenameWithShard {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type CreateFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateFileResp) Reset() {
	*x = CreateFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResp) ProtoMessage() {}

func (x *CreateFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResp.ProtoReflect.Descriptor instead.
func (*CreateFileResp) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{7}
}

type DeleteFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	File   string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *DeleteFileReq) Reset() {
	*x = DeleteFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileReq) ProtoMessage() {}

func (x *DeleteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileReq.ProtoReflect.Descriptor instead.
func (*DeleteFileReq) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DeleteFileReq) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type DeleteFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunks []*ChunkFilenameWithShard `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
}

func (x *DeleteFileResp) Reset() {
	*x = DeleteFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResp) ProtoMessage() {}

func (x *DeleteFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResp.ProtoReflect.Descriptor instead.
func (*DeleteFileResp) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFileResp) GetChunks() []*ChunkFilenameWithShard {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkFilenameWithShard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Shard    string `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
}

func (x *ChunkFilenameWithShard) Reset() {
	*x = ChunkFilenameWithShard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkFilenameWithShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkFilenameWithShard) ProtoMessage() {}

func (x *ChunkFilenameWithShard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkFilenameWithShard.ProtoReflect.Descriptor instead.
func (*ChunkFilenameWithShard) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{10}
}

func (x *ChunkFilenameWithShard) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ChunkFilenameWithShard) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

type GetFileChunksReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	File   string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *GetFileChunksReq) Reset() {
	*x = GetFileChunksReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileChunksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileChunksReq) ProtoMessage() {}

func (x *GetFileChunksReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileChunksReq.ProtoReflect.Descriptor instead.
func (*GetFileChunksReq) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileChunksReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetFileChunksReq) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type GetFileChunksResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunks      []*ChunkFilenameWithShard `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	ContentType string                    `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
}

func (x *GetFileChunksResp) Reset() {
	*x = GetFileChunksResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meta_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileChunksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileChunksResp) ProtoMessage() {}

func (x *GetFileChunksResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meta_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileChunksResp.ProtoReflect.Descriptor instead.
func (*GetFileChunksResp) Descriptor() ([]byte, []int) {
	return file_proto_meta_proto_rawDescGZIP(), []int{12}
}

func (x *GetFileChunksResp) GetChunks() []*ChunkFilenameWithShard {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *GetFileChunksResp) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_proto_meta_proto protoreflect.FileDescriptor

var file_proto_meta_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x29, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x25, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x24, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x22, 0x94, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x52, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3b, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x46, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x06, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x73, 0x22, 0x4a, 0x0a, 0x16, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x68, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x22, 0x3e, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x6c, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x34, 0x0a, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x46,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x52, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x32, 0x85, 0x03, 0x0a, 0x12,
	0x41, 0x70, 0x69, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x12, 0x11, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x13, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x42, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73,
	0x12, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x3b, 0x6d, 0x65, 0x74,
	0x61, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_meta_proto_rawDescOnce sync.Once
	file_proto_meta_proto_rawDescData = file_proto_meta_proto_rawDesc
)

func file_proto_meta_proto_rawDescGZIP() []byte {
	file_proto_meta_proto_rawDescOnce.Do(func() {
		file_proto_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_meta_proto_rawDescData)
	})
	return file_proto_meta_proto_rawDescData
}

var file_proto_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_meta_proto_goTypes = []interface{}{
	(*CreateBucketReq)(nil),        // 0: meta.CreateBucketReq
	(*CreateBucketResp)(nil),       // 1: meta.CreateBucketResp
	(*DeleteBucketReq)(nil),        // 2: meta.DeleteBucketReq
	(*DeleteBucketResp)(nil),       // 3: meta.DeleteBucketResp
	(*GetFilesReq)(nil),            // 4: meta.GetFilesReq
	(*GetFilesResp)(nil),           // 5: meta.GetFilesResp
	(*CreateFileReq)(nil),          // 6: meta.CreateFileReq
	(*CreateFileResp)(nil),         // 7: meta.CreateFileResp
	(*DeleteFileReq)(nil),          // 8: meta.DeleteFileReq
	(*DeleteFileResp)(nil),         // 9: meta.DeleteFileResp
	(*ChunkFilenameWithShard)(nil), // 10: meta.ChunkFilenameWithShard
	(*GetFileChunksReq)(nil),       // 11: meta.GetFileChunksReq
	(*GetFileChunksResp)(nil),      // 12: meta.GetFileChunksResp
}
var file_proto_meta_proto_depIdxs = []int32{
	10, // 0: meta.CreateFileReq.chunks:type_name -> meta.ChunkFilenameWithShard
	10, // 1: meta.DeleteFileResp.chunks:type_name -> meta.ChunkFilenameWithShard
	10, // 2: meta.GetFileChunksResp.chunks:type_name -> meta.ChunkFilenameWithShard
	0,  // 3: meta.ApiWithMetaService.CreateBucket:input_type -> meta.CreateBucketReq
	2,  // 4: meta.ApiWithMetaService.DeleteBucket:input_type -> meta.DeleteBucketReq
	4,  // 5: meta.ApiWithMetaService.GetFiles:input_type -> meta.GetFilesReq
	6,  // 6: meta.ApiWithMetaService.CreateFile:input_type -> meta.CreateFileReq
	8,  // 7: meta.ApiWithMetaService.DeleteFile:input_type -> meta.DeleteFileReq
	11, // 8: meta.ApiWithMetaService.GetFileChunks:input_type -> meta.GetFileChunksReq
	1,  // 9: meta.ApiWithMetaService.CreateBucket:output_type -> meta.CreateBucketResp
	3,  // 10: meta.ApiWithMetaService.DeleteBucket:output_type -> meta.DeleteBucketResp
	5,  // 11: meta.ApiWithMetaService.GetFiles:output_type -> meta.GetFilesResp
	7,  // 12: meta.ApiWithMetaService.CreateFile:output_type -> meta.CreateFileResp
	9,  // 13: meta.ApiWithMetaService.DeleteFile:output_type -> meta.DeleteFileResp
	12, // 14: meta.ApiWithMetaService.GetFileChunks:output_type -> meta.GetFileChunksResp
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_meta_proto_init() }
func file_proto_meta_proto_init() {
	if File_proto_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBucketReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBucketResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBucketReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBucketResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFilesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFilesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunkFilenameWithShard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileChunksReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meta_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileChunksResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_meta_proto_goTypes,
		DependencyIndexes: file_proto_meta_proto_depIdxs,
		MessageInfos:      file_proto_meta_proto_msgTypes,
	}.Build()
	File_proto_meta_proto = out.File
	file_proto_meta_proto_rawDesc = nil
	file_proto_meta_proto_goTypes = nil
	file_proto_meta_proto_depIdxs = nil
}
